export async function main(): Promise<void> {
}

main()
	.catch((err) => {
		console.log(err);
	});